# Generated by Django 3.0.3 on 2020-07-05 11:20

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200702_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreported',
            name='problem_id',
            field=models.CharField(blank=True, default=reports.models.random_code, max_length=12, unique=True),
        ),
    ]
